"""case studies and platform resources

Revision ID: 3d0072f3c82f
Revises: 7c2e5d9a1b43
Create Date: 2026-09-24 09:07:35.226761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d0072f3c82f'
down_revision = '7c2e5d9a1b43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('icon', sa.String(length=40), nullable=False),
    sa.Column('color', sa.String(length=16), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_case_categories')),
    sa.UniqueConstraint('slug', name=op.f('uq_case_categories_slug'))
    )
    op.create_table('case_section_titles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_ka', sa.String(length=120), nullable=False),
    sa.Column('name_en', sa.String(length=120), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_case_section_titles'))
    )
    op.create_table('case_category_translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('locale', sa.String(length=5), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['case_categories.id'], name=op.f('fk_case_category_translations_category_id_case_categories'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_case_category_translations')),
    sa.UniqueConstraint('category_id', 'locale', name='uq_case_category_locale')
    )
    op.create_table('case_studies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('cover_media_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['case_categories.id'], name=op.f('fk_case_studies_category_id_case_categories'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['cover_media_id'], ['media_files.id'], name=op.f('fk_case_studies_cover_media_id_media_files'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_case_studies_created_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_case_studies')),
    sa.UniqueConstraint('slug', name=op.f('uq_case_studies_slug'))
    )
    op.create_table('resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('media_id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('title_ka', sa.String(length=200), nullable=False),
    sa.Column('title_en', sa.String(length=200), nullable=False),
    sa.Column('description_ka', sa.Text(), nullable=False),
    sa.Column('description_en', sa.Text(), nullable=False),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_resources_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['media_id'], ['media_files.id'], name=op.f('fk_resources_media_id_media_files'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resources'))
    )
    op.create_table('case_study_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_study_id', sa.Integer(), nullable=False),
    sa.Column('media_id', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('caption_ka', sa.String(length=255), nullable=False),
    sa.Column('caption_en', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_study_id'], ['case_studies.id'], name=op.f('fk_case_study_images_case_study_id_case_studies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['media_id'], ['media_files.id'], name=op.f('fk_case_study_images_media_id_media_files'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_case_study_images'))
    )
    op.create_table('case_study_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_study_id', sa.Integer(), nullable=False),
    sa.Column('title_id', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('body_ka', sa.Text(), nullable=False),
    sa.Column('body_en', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_study_id'], ['case_studies.id'], name=op.f('fk_case_study_sections_case_study_id_case_studies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['title_id'], ['case_section_titles.id'], name=op.f('fk_case_study_sections_title_id_case_section_titles'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_case_study_sections'))
    )
    op.create_table('case_study_translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_study_id', sa.Integer(), nullable=False),
    sa.Column('locale', sa.String(length=5), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('about', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['case_study_id'], ['case_studies.id'], name=op.f('fk_case_study_translations_case_study_id_case_studies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_case_study_translations')),
    sa.UniqueConstraint('case_study_id', 'locale', name='uq_case_study_locale')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('case_study_translations')
    op.drop_table('case_study_sections')
    op.drop_table('case_study_images')
    op.drop_table('resources')
    op.drop_table('case_studies')
    op.drop_table('case_category_translations')
    op.drop_table('case_section_titles')
    op.drop_table('case_categories')
    # ### end Alembic commands ###
