"""Import every model so SQLAlchemy metadata (and Alembic) sees all tables."""

from app.models.achievement import Achievement, UserAchievement
from app.models.assessment import Question, QuestionOption, Quiz, QuizAnswer, QuizAttempt
from app.models.assignment import Assignment, AssignmentSubmission, Grade
from app.models.audit import AuditLog
from app.models.base import (
    AttemptStatus,
    BookmarkType,
    CourseStatus,
    Difficulty,
    EnrollmentMode,
    EnrollmentStatus,
    FeedbackMode,
    LessonType,
    MediaKind,
    Platform,
    ProgressStatus,
    QuestionType,
    ReviewStatus,
    SubmissionStatus,
    SubmissionType,
    UserStatus,
    utcnow,
)
from app.models.case_study import (
    CaseCategory,
    CaseCategoryTranslation,
    CaseSectionTitle,
    CaseStudy,
    CaseStudyImage,
    CaseStudySection,
    CaseStudyTranslation,
)
from app.models.certificate import Certificate
from app.models.course import (
    Category,
    CategoryTranslation,
    Course,
    CourseTranslation,
    Lesson,
    LessonResource,
    LessonTranslation,
    Module,
    ModuleTranslation,
    course_categories,
)
from app.models.cyberhero import (
    CyberAgreementClause,
    CyberAgreementSection,
    CyberArticle,
    CyberArticleBlock,
    CyberArticleSource,
    CyberBranch,
    CyberBranchChoice,
    CyberBranchMessage,
    CyberCertificate,
    CyberKnowledgeChunk,
    CyberKnowledgeSection,
    CyberMascotReaction,
    CyberMascotTip,
    CyberMission,
    CyberMissionNote,
    CyberMissionRound,
    CyberProgress,
    CyberRoundItem,
    CyberSafetyResource,
    CyberTrack,
)
from app.models.enrollment import Bookmark, CourseProgress, Enrollment, LessonProgress
from app.models.media import MediaFile
from app.models.notification import Notification
from app.models.resource import Resource
from app.models.settings import FeatureFlag, SiteSetting
from app.models.social import Discussion, DiscussionPost, DiscussionReport, Review
from app.models.user import AuthToken, Permission, Role, User, role_permissions, user_roles

__all__ = [
    "Achievement",
    "Assignment",
    "AssignmentSubmission",
    "AttemptStatus",
    "AuditLog",
    "AuthToken",
    "Bookmark",
    "BookmarkType",
    "CaseCategory",
    "CaseCategoryTranslation",
    "CaseSectionTitle",
    "CaseStudy",
    "CaseStudyImage",
    "CaseStudySection",
    "CaseStudyTranslation",
    "Category",
    "CategoryTranslation",
    "Certificate",
    "Course",
    "CourseProgress",
    "CourseStatus",
    "CourseTranslation",
    "CyberAgreementClause",
    "CyberAgreementSection",
    "CyberArticle",
    "CyberArticleBlock",
    "CyberArticleSource",
    "CyberBranch",
    "CyberBranchChoice",
    "CyberBranchMessage",
    "CyberCertificate",
    "CyberKnowledgeChunk",
    "CyberKnowledgeSection",
    "CyberMascotReaction",
    "CyberMascotTip",
    "CyberMission",
    "CyberMissionNote",
    "CyberMissionRound",
    "CyberProgress",
    "CyberRoundItem",
    "CyberSafetyResource",
    "CyberTrack",
    "Difficulty",
    "Discussion",
    "DiscussionPost",
    "DiscussionReport",
    "Enrollment",
    "EnrollmentMode",
    "EnrollmentStatus",
    "FeatureFlag",
    "FeedbackMode",
    "Grade",
    "Lesson",
    "LessonProgress",
    "LessonResource",
    "LessonTranslation",
    "LessonType",
    "MediaFile",
    "MediaKind",
    "Module",
    "ModuleTranslation",
    "Notification",
    "Permission",
    "Platform",
    "ProgressStatus",
    "Question",
    "QuestionOption",
    "QuestionType",
    "Quiz",
    "QuizAnswer",
    "QuizAttempt",
    "Resource",
    "Review",
    "ReviewStatus",
    "Role",
    "SiteSetting",
    "SubmissionStatus",
    "SubmissionType",
    "User",
    "UserAchievement",
    "UserStatus",
    "course_categories",
    "role_permissions",
    "user_roles",
    "utcnow",
]
